//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiUDS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int codigo { get; set; }
        public string tamanho { get; set; }
        public string sabor { get; set; }
        public string personalizacao { get; set; }
        public Nullable<decimal> valortotal { get; set; }
        public Nullable<int> tempopreparo { get; set; }
    }
}
